[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "texact"
version = "0.1.0"
description = "Automated LaTeX reviewer checks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["Pillow>=10", "colorama>=0.4"]

[project.scripts]
texact = "texact:main"

[tool.setuptools]
package-dir = {"" = "source"}
packages = ["texact_config", "reviewers"]
py-modules = [
  "printer",
  "template_check",
  "texact",
]

[project.optional-dependencies]
docs = [
    "sphinx>=7",
    "furo>=2025",
    "myst-parser>=4",
    "m2r2",
    "docutils<=0.20",
]

[tool.setuptools.package-data]
texact_config = ["chktexrc"]
