[build-system]
requires = ["setuptools>=68", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "texact"
dynamic = ['version']
description = "Automated article and LaTeX checks"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["Pillow>=10", "colorama>=0.4"]
authors = [
    { name = "Theodor Lindberg" },
]

[project.scripts]
texact = "texact:main"

[tool.setuptools]
package-dir = {"" = "source"}
packages = ["texact_config", "reviewers"]
py-modules = [
  "configuration",
  "printer",
  "template_check",
  "texact",
]

[project.optional-dependencies]
docs = [
    "sphinx>=7,<9",
    "furo>=2025",
    "myst-parser>=4",
    "m2r2",
    "docutils<=0.20",
    "sphinx-multiversion==0.2.4",
]

[tool.setuptools.package-data]
texact_config = ["chktexrc"]

[tool.setuptools_scm]
version_scheme = "release-branch-semver"
local_scheme = "node-and-date"
parentdir_prefix_version = "texact-"
fallback_version = "0.0+UNKNOWN"
